### ISSUE TITLE
Doesn't seem to work with node 12 as advertised

### ISSUE THREAD

**Issue by kenlyon** [sapics/gulp#4]
I'm using node 12.18.2 and gulp-v3@3.12.1. When I try to run a gulp command, I'm still seeing the same "primordials is not defined" error that I get from gulp@3.9.1.

Am I missing something with the setup, or are there still issues with node 12?

It'd be really great if this worked, as it'd save me a lot of time re-writing my gulpfile to work with gulp@4.x.

**Comment by kenlyon** [comment]
The call stack showed that the version of fs.js being used was from graceful-fs within the gulp module, not gulp-v3.

I was executing gulp from the command line after doing `npm install -g gulp-v3`. Despite `gulp -v` returning 3.12.1 foir both CLI and Local version, it still seemed to be loading fs.js from within gulp, not gulp-v3.

I understand from [this answer](https://stackoverflow.com/a/58394828) that the graceful-fs dependency is the heart of the problem.

**Comment by sapics** [comment]
The answer which you noticed would be the best way, I think :)
We need to replace `require("gulp")` to `require("gulp-v3")`, did you do that?

**Comment by kenlyon** [comment]
Yes, I did do that. However, there are a few complications. In one case I saw an error that the gulp module was missing (an error message within gulp-v3, so I re-installed `gulp` alongside it, which might have complicated things.

I also know that I use `gulp-sequence` which unfortunately seems to require `gulp` rather than `gulp-v3`. I don't know if I'd need to fork it in order to make it work.

**Comment by sapics** [comment]
I created https://www.npmjs.com/package/run-sequence-v3 also, it might be work ;)

**Comment by kenlyon** [comment]
I've been able to replace `gulp-sequence` with `run-sequence-v3` and it seems to be able to run my gulp tasks successfully. (Not tested every single one yet, but the main ones like building look good.)

Also, I found why I was getting confused about needing to install `gulp` as well as `gulp-v3`. In some cases, I was seeing this error:
```
Local gulp not found in {path}
Try running: npm install gulp
```
This had led me to think that you needed `gulp` to be installed as well. I've since discovered that this is an old message from the original repository. You should probably recaption it to "Try running: npm install gulp-v3".

When I run my build in Azure Devops, it's showing that error. I'll do some troubleshooting to find out why.

**Comment by kenlyon** [comment]
I'll close this issue as it was my own mistake to have `gulp` installed at the same time. I'd suggest you update that message to reduce confusion, though. :)
